src/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('home/', include('teacher.urls', namespace='home'))   

]

teacher/urls.py
from django.urls import path

from . import views

app_name= 'teacher'

urlpatterns = [
    path('', views.courses , name= "courses"),
    path('create', views.course_new , name= "new_course"),
    path('<int:id>', views.course , name= 'course'),
    path('edit/<int:id>', views.course_edit , name= 'edit_course'),
    path('delete/<int:id>', views.course_del , name= 'delete_course'),
]

student/models.py
from django.db import models
from django.contrib.auth.models import User
from teacher.models import Courses

# Create your models here.

class Student(models.Model):
    User = models.OneToOneField(User, on_delete=models.CASCADE)
    stu_name = models.CharField(max_length=80)
    stu_age = models.IntegerField()
    stu_conf = models.ManyToManyField("teacher.Courses", related_name="students")

    def __str__(self):
        return self.stu_name

teacher/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.


class Teacher(models.Model):
    User = models.OneToOneField(User, on_delete=models.CASCADE)
    tea_name = models.CharField(max_length=90)
    discraptions = models.CharField( max_length=500)



    def __str__(self):

        return self.tea_name
    

class Courses(models.Model):


    cour_name = models.CharField(max_length=60)
    cour_date = models.DateField(default=datetime.date.today)
    cour_price = models.DecimalField(max_digits=10, decimal_places=2)
    teachar_conf = models.ForeignKey("Teacher",on_delete=models.CASCADE, related_name="courses")



    def __str__(self):
        return self.cour_name

    

student/views.py
from django.shortcuts import render

# Create your views here.

teacher/views.py
from django.shortcuts import render, redirect

from django.views.generic import ListView, DetailView      
from .models import Teacher, Courses

from .form import CourseForm


# Create your views here.


def courses(request):
    all_courses = Courses.objects.all()
    
    return render(request,"teacher/course_list.html",{"all_courses":all_courses})






def course(request, id):
    lesson = Courses.objects.get(id=id)

    return render(request,"teacher/course_detail.html",{"lesson":lesson})   




def course_edit(request, id):
    lesson = Courses.objects.get(id=id)
    if request.method == "POST":
        form = CourseForm(request.POST , instance=lesson)
        if form.is_valid():
            form.save()
            return redirect("home:courses") 

    else:
        form= CourseForm(instance=lesson)

    return render (request, "teacher/course_edit.html", {"form":form} )


def course_new(request):

    if request.method == "POST":
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home:courses") 

    else:
        form= CourseForm()

    return render (request, "teacher/course_new.html", {"form":form} )




def course_del(request, id):
    lesson = Courses.objects.get(id=id)
    lesson.delete()
    return redirect("home:courses") 




"""

class CoursesList(ListView):
    model = Courses
    context_object_name = 'courses'
    template_name=''
    def get_queryset(self):
        return Courses.objects.select_related('Teacher')
    





class CoursesDetail(DetailView):
    model = Courses
    template_name=''
    context_object_name = 'course'
    def get_queryset(self):
        return Courses.objects.select_related('Teacher').prefetch_related('students')
    
"""

teacher/templates/teacher/course_detail.html
<h2> welcome in our course</h2>

<hr>
    <a href="{% url 'home:edit_course' lesson.id %}">edit this course</a> 
<hr>


{{lesson}}


<hr>
<form method="POST" action=" {% url 'home:delete_course' lesson.id %}">
  {% csrf_token %}

  <input type="submit" name="delete" value="delete">

</form>

teacher/templates/teacher/course_edit.html
<h2> edit this course</h2>




<form method="POST" action="">
    {% csrf_token %}
    {{form}}

    <input type="submit" value="edit">
</form>

teacher/templates/teacher/course_list.html
<h2> welcome in our page</h2>

<hr>

    <a href="{% url 'home:new_course' %}">add new course</a> 

<hr>

{% for course in all_courses %}
    <h4>
    <a href="{% url 'home:course' course.id %}">{{course.cour_name}}</a> 
    </h4>
{% endfor %}

teacher/templates/teacher/course_new.html
<h2> add new course</h2>


<form method="POST" action="">
    {% csrf_token %}
    {{form}}

    <input type="submit" value="add">
</form>